name: Aaqa Ishtyaq - FullStack developer
email: aaqaishtyaq@gmail.com
markdown: kramdown
url: "https://aaqa.dev"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude: ["node_modules", "gulpfile.js", "package.json", "vendor"]
kramdown:
    input: GFM
    syntax_highlighter: rouge
permalink: /notes/:title
baseurl: /
keep_files: [assets]
incremental: true
